# Generated by Django 3.0.2 on 2020-02-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_project_masterkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositories',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
