# Generated by Django 3.0.2 on 2020-02-16 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0004_repositories_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositories',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
